### ISSUE TITLE
issue while running the code

### ISSUE THREAD

**Issue by bhralz** [SanthiyaDaniel/Impact-of-COVID-19#1]
while testing the code the below error occurred:
#
"**name 'newdf2' is not defined**"

#
Also, neewdf3 was not defined.

please reply on how to cover this?!
thanks for all of your help.

**Comment by bhralz** [comment]
Dear Santhiya
please check the entire code as soon as possible.

**Comment by SanthiyaDaniel** [comment]
Hi,

Please find the updated codes. Those were additional plots I added apart form the ones discussed. Now you can run them
